name: Run Gemini CLI

on:
  workflow_dispatch:

jobs:
  run-gemini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Show Gemini CLI help
        run: gemini --help

      - name: Run Gemini prompt
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: gemini -p "Hello Gemini, give me short motivational quote"
